
version: '3.1'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    volumes:
      - /var/lib/mysql
      - ../data/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: resume
  php_admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: resume
